
services:
  backend:
    container_name: red-tetris-backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./shared:/app/shared
      - ./backend:/app/backend
      - ./backend/node_modules:/app/backend/node_modules
    networks:
      - red-tetris
    environment:
      - NODE_ENV=development

  frontend:
    container_name: red-tetris-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./shared:/app/shared
      - ./frontend:/app/frontend
      - ./frontend/node_modules:/app/frontend/node_modules
    networks:
      - red-tetris
    environment:
      - NODE_ENV=development
      - VITE_SERVER_URL=http://localhost:8000
    depends_on:
      - backend

networks:
  red-tetris:
    driver: bridge
